### ISSUE TITLE
Convert readme to rst format so pypi page looks nice

### ISSUE THREAD

**Issue by mstevens83** [ExCiteS/geokey#328]
Compare this: https://pypi.python.org/pypi/geokey-sapelli

To this: https://pypi.python.org/pypi/geokey

I think the pypi page for geokey is so ugly because the readme file is in Markdown format, while the one of geokey-sapelli is in rst format.

**Comment by EmpressNaledi** [comment]
I know nothing, but it's definitely prettier!

On 16/12/2015 19:45, Matthias Stevens wrote:
>
> Compare this: https://pypi.python.org/pypi/geokey-sapelli
>
> To this: https://pypi.python.org/pypi/geokey
>
> I think the pypi page for geokey is so ugly because the readme file is 
> in Markdown format, while the one of geokey-sapelli is in rst format.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ExCiteS/geokey/issues/328>.
>


-- 
-- 
Louise Francis
Co-founder & Chief Executive
Tel: 020 7679 2296
Email: Louise Francis <mailto:l.francis@mappingforchange.org.uk>
Mapping for Change
Chorley Institute
University College London (UCL)
Gower St. London WC1E 6BT
www.mappingforchange.org.uk <http://www.mappingforchange.org.uk>
www.communitymaps.org.uk <http://www.communitymaps.org.uk>
Twitter <http://www.twitter.com/#%21/Mapping4Change>
Level 2 Award Winner Summer 2010 Supported by:

www.UnLtd.org.uk

------------------------------------------------------------------------
The information contained in and accompanying this communication has 
been provided via email at your request and may be confidential, subject 
to legal privilege, or otherwise protected from disclosure, and is 
intended solely for the use of the intended recipient(s). If you are not 
the intended recipient(s) of this communication, please delete and 
destroy all copies in your possession, notify 
l.francis@mappingforchange.org.uk that you have received this 
communication in error, and note that any review or dissemination of, or 
the taking of any action in reliance on, this communication is expressly 
prohibited. E-mail messages are not secure and may contain computer 
viruses or other defects, may not be accurately replicated on other 
systems, or may be intercepted, read, and/or amended by unauthorized 
persons without the knowledge of the sender or the intended recipient. 
Information sent by email is at your sole risk, and Mapping for Change 
(i) makes no warranties in relation to the foregoing matters, (ii) 
accepts no liability for any effects that they may have including 
rendering information inaccurate or incomplete and (iii) has no 
responsibility for any unauthorized access. Please note that Mapping for 
Change reserves the right to intercept, monitor and retain e-mail 
messages to and from its systems as permitted by applicable law. You 
understand that this communication shall only be deemed to have been 
delivered upon actual receipt by the intended recipient.
